/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ppe_v2;

/**
 *
 * @author theop_e0sot23
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        produitList3.init();
        produitList2.init();
        produitList1.init();
        profils1.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        produitList1 = new com.mycompany.ppe_v2.ProduitList();
        produitList2 = new com.mycompany.ppe_v2.ProduitList();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        produitList3 = new com.mycompany.ppe_v2.ProduitList();
        client1 = new com.mycompany.ppe_v2.Client();
        profils1 = new com.mycompany.ppe_v2.Profils();
        vente1 = new com.mycompany.ppe_v2.Vente();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addTab("Produit", produitList3);
        jTabbedPane1.addTab("Client", client1);
        jTabbedPane1.addTab("Profils", profils1);
        jTabbedPane1.addTab("Ventes", vente1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.ppe_v2.Client client1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.mycompany.ppe_v2.ProduitList produitList1;
    private com.mycompany.ppe_v2.ProduitList produitList2;
    private com.mycompany.ppe_v2.ProduitList produitList3;
    private com.mycompany.ppe_v2.Profils profils1;
    private com.mycompany.ppe_v2.Vente vente1;
    // End of variables declaration//GEN-END:variables
}
