/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ppe_v2;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author theop_e0sot23
 */
public class ProduitList extends javax.swing.JPanel {

    
    /**
     * Creates new form ProduitList
     */
    public ProduitList() {
        initComponents();
    }
    
    public void init(){
        catBDD();
        clientBDD();
    }
    
    //Connection recup = new Connection();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogMod = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListDetail = new javax.swing.JList<>();
        jButtonModifierValue = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jTextFieldMod = new javax.swing.JTextField();
        jDialogAdd = new javax.swing.JDialog();
        jButtonAddProduit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxCatAdd = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNomProduit = new javax.swing.JTextField();
        jTextFieldStock = new javax.swing.JTextField();
        jTextFieldTarif = new javax.swing.JTextField();
        jTextFieldPop = new javax.swing.JTextField();
        jDialogVendre = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldQuantite = new javax.swing.JTextField();
        jLabelPrixT = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelPrixU = new javax.swing.JLabel();
        jButtonClcPrix = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxClient = new javax.swing.JComboBox<>();
        jLabelName = new javax.swing.JLabel();
        jButtonEncaisser = new javax.swing.JButton();
        jLabelNameL = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProduit = new javax.swing.JList<>();
        jButtonProduit = new javax.swing.JButton();
        jButtonAfficherProduit = new javax.swing.JButton();
        jComboBoxCat = new javax.swing.JComboBox<>();
        jButtonVendre = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();

        jListDetail.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jListDetail);

        jButtonModifierValue.setText("Modifier");
        jButtonModifierValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierValueActionPerformed(evt);
            }
        });

        jButtonSave.setText("Sauver");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogModLayout = new javax.swing.GroupLayout(jDialogMod.getContentPane());
        jDialogMod.getContentPane().setLayout(jDialogModLayout);
        jDialogModLayout.setHorizontalGroup(
            jDialogModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogModLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(jDialogModLayout.createSequentialGroup()
                        .addGroup(jDialogModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModifierValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMod)))
                .addContainerGap())
        );
        jDialogModLayout.setVerticalGroup(
            jDialogModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogModLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModifierValue)
                    .addComponent(jTextFieldMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonAddProduit.setText("Ajouter");
        jButtonAddProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProduitActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom du produit");

        jLabel2.setText("Tarif");

        jLabel3.setText("Popularite");

        jLabel4.setText("Stock");

        jComboBoxCatAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCatAddActionPerformed(evt);
            }
        });

        jLabel5.setText("Categorie");

        javax.swing.GroupLayout jDialogAddLayout = new javax.swing.GroupLayout(jDialogAdd.getContentPane());
        jDialogAdd.getContentPane().setLayout(jDialogAddLayout);
        jDialogAddLayout.setHorizontalGroup(
            jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDialogAddLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogAddLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogAddLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jDialogAddLayout.createSequentialGroup()
                                .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxCatAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPop, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAddProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jDialogAddLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNomProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jDialogAddLayout.setVerticalGroup(
            jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCatAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAddProduit)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jLabel7.setText("Quantité");

        jTextFieldQuantite.setText("1");

        jLabel9.setText("Prix unitaire");

        jButtonClcPrix.setText("Calculer prix");
        jButtonClcPrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClcPrixActionPerformed(evt);
            }
        });

        jLabel8.setText("id Client");

        jComboBoxClient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        jComboBoxClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClientActionPerformed(evt);
            }
        });

        jLabelName.setText("Nom");

        jButtonEncaisser.setText("Encaisser la moula");
        jButtonEncaisser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncaisserActionPerformed(evt);
            }
        });

        jLabel6.setText("Prix");

        javax.swing.GroupLayout jDialogVendreLayout = new javax.swing.GroupLayout(jDialogVendre.getContentPane());
        jDialogVendre.getContentPane().setLayout(jDialogVendreLayout);
        jDialogVendreLayout.setHorizontalGroup(
            jDialogVendreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogVendreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogVendreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogVendreLayout.createSequentialGroup()
                        .addGroup(jDialogVendreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEncaisser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jDialogVendreLayout.createSequentialGroup()
                                .addGroup(jDialogVendreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jDialogVendreLayout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(jDialogVendreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDialogVendreLayout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jTextFieldQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonClcPrix))
                                    .addComponent(jLabelPrixT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jDialogVendreLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jComboBoxClient, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(8, 8, 8))
                    .addGroup(jDialogVendreLayout.createSequentialGroup()
                        .addGroup(jDialogVendreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDialogVendreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogVendreLayout.createSequentialGroup()
                                .addComponent(jLabelPrixU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabelNameL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jDialogVendreLayout.setVerticalGroup(
            jDialogVendreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogVendreLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jDialogVendreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNameL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogVendreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabelPrixU, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogVendreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jButtonClcPrix))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogVendreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPrixT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogVendreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEncaisser)
                .addContainerGap())
        );

        jListProduit.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jListProduit);

        jButtonProduit.setText("Les produits");
        jButtonProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProduitActionPerformed(evt);
            }
        });

        jButtonAfficherProduit.setText("Afficher le produit");
        jButtonAfficherProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAfficherProduitActionPerformed(evt);
            }
        });

        jComboBoxCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        jComboBoxCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCatActionPerformed(evt);
            }
        });

        jButtonVendre.setText("Vendre");
        jButtonVendre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVendreActionPerformed(evt);
            }
        });

        jButtonAdd.setText("Ajouter");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonProduit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAfficherProduit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonVendre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAdd)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonProduit)
                    .addComponent(jButtonAfficherProduit)
                    .addComponent(jComboBoxCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVendre)
                    .addComponent(jButtonAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

        /**
     * Récupere les champ dans la base de donnée
     */
    public void clientBDD(){
        DefaultComboBoxModel cat = (DefaultComboBoxModel) jComboBoxClient.getModel();
        ResultSet requete = DaoSIO.getInstance().requeteSelection("select * from client");
        try{
            while(requete.next()){
                CategorieCombo cc = new CategorieCombo(requete.getString("idClient"), requete.getString("nom"));
                cat.addElement(cc);
            }
        } catch(SQLException ex) {
            Logger.getLogger(ProduitList.class.getName()).log(Level.SEVERE, null, ex);

        }
    }
    
    /**
     * Récupere les champ dans la base de donnée
     */
    public void catBDD(){
        DefaultComboBoxModel cat = (DefaultComboBoxModel) jComboBoxCat.getModel();
        DefaultComboBoxModel catA = (DefaultComboBoxModel) jComboBoxCatAdd.getModel();
        ResultSet requete = DaoSIO.getInstance().requeteSelection("select * from categorie");
        try{
            while(requete.next()){
                CategorieCombo cc = new CategorieCombo(requete.getString("idCat"), requete.getString("nomCat"));
                cat.addElement(cc);
                catA.addElement(cc);
            }
        } catch(SQLException ex) {
            Logger.getLogger(ProduitList.class.getName()).log(Level.SEVERE, null, ex);

        }
        
    }
    
    
    /**
     * Selectionne la valeur surligné
     * @param evt 
     */
    private void jButtonModifierValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierValueActionPerformed
        DefaultListModel produit = (DefaultListModel) jListDetail.getModel();
        int index = jListDetail.getSelectedIndex();
        System.out.println(index);

        if(index != -1){
            try{
               jTextFieldMod.setText(produit.getElementAt(jListDetail.getSelectedIndex()).toString());
             
               
            }catch(Exception ex){
                Logger.getLogger(ProduitList.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jButtonModifierValueActionPerformed

    /**
     * Update la base de donnee. Ou sauvegarde les modification apportées sur le produit
     *
     * @param evt 
     */
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        DefaultListModel mProduit = (DefaultListModel) jListDetail.getModel();
        int index = jListDetail.getSelectedIndex();
        if(index != -1){
            try{
                ResultSet dProduit = DaoSIO.getInstance().requeteSelection("select * from produit");
                switch(index){
                    case 1:
                        if(dProduit.next()){
                            DaoSIO.getInstance().requeteAction("update produit set nomProduit = '" + jTextFieldMod.getText() + "' where idProduit = '" + mProduit.get(0) +"'");
                            System.out.println("la requete passe");
                        } else {
                            System.out.println("ca marche pas t con");
                        }
                        break;
                    case 2:
                        if(dProduit.next()){
                            DaoSIO.getInstance().requeteAction("update produit set tarif = '" + jTextFieldMod.getText() + "' where idProduit = '" + mProduit.get(0) +"'");
                            System.out.println("la requete passe");
                            
                        } else {
                            System.out.println("ca marche pas t con");
                        }
                        break;
                    case 3:
                        if(dProduit.next()){
                            DaoSIO.getInstance().requeteAction("update produit set stock = '" + jTextFieldMod.getText() + "' where idProduit = '" + mProduit.get(0) +"'");
                            System.out.println("la requete passe");
                            
                        } else {
                            System.out.println("ca marche pas t con");
                        }
                        break;
                    case 4:
                        if(dProduit.next()){
                            DaoSIO.getInstance().requeteAction("update produit set popularite = '" + jTextFieldMod.getText() + "' where idProduit = '" + mProduit.get(0) +"'");
                            System.out.println("la requete passe");
                            
                        } else {
                            System.out.println("ca marche pas t con");
                        }
                        break;
                }
            }catch(SQLException ex){
                Logger.getLogger(ProduitList.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * Inser un produit dans la base de donnée 
     * @param evt 
     */
    private void jButtonAddProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProduitActionPerformed
        CategorieCombo cca = (CategorieCombo) jComboBoxCatAdd.getSelectedItem();
        int ajouter = DaoSIO.getInstance().requeteAction("insert into produit(nomProduit, tarif, stock, popularite, id_categorie) values ('" + jTextFieldNomProduit.getText() + "', '"+ jTextFieldTarif.getText() +"', '"+ jTextFieldStock.getText() +"', '"+ jTextFieldPop.getText() +"', '"+ cca.getId() +"')");

    }//GEN-LAST:event_jButtonAddProduitActionPerformed

    private void jComboBoxCatAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCatAddActionPerformed

    }//GEN-LAST:event_jComboBoxCatAddActionPerformed

    /**
     * Fait le calcul du prix en fonction de la quantité de produit selectionnée
     * @param evt 
     */
    private void jButtonClcPrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClcPrixActionPerformed
        int mescouilles;
        try {
            ResultSet dProduit = DaoSIO.getInstance().requeteSelection("select * from produit");
            while(dProduit.next()){
                if (jListProduit.getSelectedValue().split(" ")[0].equalsIgnoreCase(dProduit.getString("idProduit"))) {
                    mescouilles = dProduit.getInt("tarif") * Integer.parseInt(jTextFieldQuantite.getText());
                    jLabelPrixT.setText(String.valueOf(mescouilles));
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(ProduitList.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonClcPrixActionPerformed

    private void jComboBoxClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxClientActionPerformed

    /**
     * Inser une vente dans la base de donnée
     * @param evt 
     */
    private void jButtonEncaisserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncaisserActionPerformed
        CategorieCombo cca = (CategorieCombo) jComboBoxClient.getSelectedItem();
        DaoSIO.getInstance().requeteAction("insert into vente(date_vente, nomPersonnel, idPersonnel, idClient, nomProduit, qte, nomClient) values (CURRENT_DATE(),'"+ Connection.nom +"', '"+ Connection.idP +"', '"+ cca.getId() +"', '"+ jLabelNameL.getText() +"', '"+ jTextFieldQuantite.getText() +"', '"+ cca.getValue() +"')");
    }//GEN-LAST:event_jButtonEncaisserActionPerformed

    
    /**
     * Affiche la liste des produit enregistré dans la base de donnée
     * @param evt 
     */
    private void jButtonProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProduitActionPerformed
        DefaultListModel produit = (DefaultListModel) jListProduit.getModel();
        produit.clear();
        CategorieCombo ccc = (CategorieCombo) jComboBoxCat.getSelectedItem();
            try {
                ResultSet lesDonnees = DaoSIO.getInstance().requeteSelection("select * from produit where id_categorie = " + ccc.getId() +"");
                while(lesDonnees.next()){
                    StringBuilder sb = new StringBuilder();
                    sb.append(lesDonnees.getString("idProduit")).append(" ");
                    sb.append(lesDonnees.getString("nomProduit")).append(" ");
                    sb.append(lesDonnees.getDouble("tarif")).append(" ");
                    sb.append(lesDonnees.getInt("stock")).append(" ");
                    sb.append(lesDonnees.getDouble("popularite"));
                    produit.addElement(sb.toString());
                }
            } catch (SQLException ex) {
                Logger.getLogger(ProduitList.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButtonProduitActionPerformed

    /**
     * Affiche le produit selecetionné pour pouvoir le modifier ou avoir plus d'info sur celui ci
     * @param evt 
     */
    private void jButtonAfficherProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAfficherProduitActionPerformed
        DefaultListModel produit = (DefaultListModel) jListDetail.getModel();

        jDialogMod.setVisible(true);
        jDialogMod.setSize(400, 300);
            try {
                ResultSet dProduit = DaoSIO.getInstance().requeteSelection("select * from produit");
                produit.removeAllElements();
                while(dProduit.next()){
                    if (jListProduit.getSelectedValue().split(" ")[0].equalsIgnoreCase(dProduit.getString("idProduit"))) {
                        produit.addElement(dProduit.getString("idProduit"));
                        produit.addElement(dProduit.getString("nomProduit"));
                        produit.addElement(dProduit.getDouble("tarif"));
                        produit.addElement(dProduit.getInt("stock"));
                        produit.addElement(dProduit.getDouble("popularite"));
                    }

                }
            } catch (SQLException ex) {
                Logger.getLogger(ProduitList.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButtonAfficherProduitActionPerformed

    private void jComboBoxCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCatActionPerformed

    }//GEN-LAST:event_jComboBoxCatActionPerformed

    /**
     * Création d'une vente en affichant sur une autre page tout les détail du produit, selection de la quatité voulu ...
     * @param evt 
     */
    private void jButtonVendreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVendreActionPerformed
        jDialogVendre.setVisible(true);
        jDialogVendre.setSize(400, 300);
            try {
                ResultSet dProduit = DaoSIO.getInstance().requeteSelection("select * from produit");
                while(dProduit.next()){
                    if (jListProduit.getSelectedValue().split(" ")[0].equalsIgnoreCase(dProduit.getString("idProduit"))) {
                        double tt = dProduit.getDouble("tarif");
                        String np = dProduit.getString("nomProduit");
                        jLabelPrixU.setText(tt + "");
                        jLabelNameL.setText(np + "");
                    }

                }
            } catch (SQLException ex) {
                Logger.getLogger(ProduitList.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButtonVendreActionPerformed

    /**
     * Affiche la page d'ajout de produit
     * @param evt 
     */
    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        jDialogAdd.setVisible(true);
        jDialogAdd.setSize(400, 300);
    }//GEN-LAST:event_jButtonAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddProduit;
    private javax.swing.JButton jButtonAfficherProduit;
    private javax.swing.JButton jButtonClcPrix;
    private javax.swing.JButton jButtonEncaisser;
    private javax.swing.JButton jButtonModifierValue;
    private javax.swing.JButton jButtonProduit;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonVendre;
    private javax.swing.JComboBox<String> jComboBoxCat;
    private javax.swing.JComboBox<String> jComboBoxCatAdd;
    private javax.swing.JComboBox<String> jComboBoxClient;
    private javax.swing.JDialog jDialogAdd;
    private javax.swing.JDialog jDialogMod;
    private javax.swing.JDialog jDialogVendre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNameL;
    private javax.swing.JLabel jLabelPrixT;
    private javax.swing.JLabel jLabelPrixU;
    private javax.swing.JList<String> jListDetail;
    private javax.swing.JList<String> jListProduit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldMod;
    private javax.swing.JTextField jTextFieldNomProduit;
    private javax.swing.JTextField jTextFieldPop;
    private javax.swing.JTextField jTextFieldQuantite;
    private javax.swing.JTextField jTextFieldStock;
    private javax.swing.JTextField jTextFieldTarif;
    // End of variables declaration//GEN-END:variables
}
