/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ppe_v2;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author theop_e0sot23
 */
public class Vente extends javax.swing.JPanel {

    /**
     * Creates new form Vente
     */
    public Vente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVente = new javax.swing.JTable();
        jButtonVente = new javax.swing.JButton();
        jButtonFacture = new javax.swing.JButton();

        jTableVente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idPodruit", "Client", "Personnel", "Quantite"
            }
        ));
        jTableVente.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(jTableVente);

        jButtonVente.setText("Afficher Ventes");
        jButtonVente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVenteActionPerformed(evt);
            }
        });

        jButtonFacture.setText("Genrerer facture");
        jButtonFacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFactureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonFacture)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVente)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVente)
                    .addComponent(jButtonFacture))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Affiche les ventes et les insere dans le tableau
     * @param evt 
     */
    private void jButtonVenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVenteActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTableVente.getModel();
            try {
                ResultSet lesDonnees = DaoSIO.getInstance().requeteSelection("select * from vente");
                while(lesDonnees.next()){
                    model.addRow(new Object[]{lesDonnees.getString("nomProduit"), lesDonnees.getString("nomClient"), lesDonnees.getString("idPersonnel"), lesDonnees.getString("qte")});

                }
            } catch (SQLException ex) {
                Logger.getLogger(ProduitList.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButtonVenteActionPerformed

    private void jButtonFactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFactureActionPerformed
       ArrayList<String> listFacture = new ArrayList();
       listFacture.add("Nike Blazer");
       listFacture.add("Nike sb pigeon");
       listFacture.add("Nike Jordan");
       listFacture.add("Nike air force one");
       new Facture(listFacture, "1000", 12);
        
    }//GEN-LAST:event_jButtonFactureActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFacture;
    private javax.swing.JButton jButtonVente;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableVente;
    // End of variables declaration//GEN-END:variables
}
